syntax on
set encoding=utf-8

set nobackup
set nowritebackup
set noswapfile

set number
set relativenumber

set shiftwidth=4
set tabstop=4
set softtabstop=4

set expandtab
set smartindent
set breakindent

set ignorecase
set smartcase
set nohlsearch

set signcolumn=yes
set scrolloff=8
set nowrap
set mouse=a

set timeoutlen=500
set updatetime=750

set undodir=~/.cache/vim/undo
set undofile

let mapleader = " "
let maplocalleader = " "

nnoremap <leader>e :Ex<cr>

"""""""""""
" gruvbox "
"""""""""""
let g:gruvbox_transparent_background = 1

set background=dark
colorscheme gruvbox


"""""""""""
" fzf.vim "
"""""""""""
nnoremap <leader>fp :GFiles<cr>
nnoremap <leader>fa :Files<cr>
nnoremap <leader>fg :Rg<cr>

"""""""""""""""
" vim-airline "
"""""""""""""""
let g:airline_theme='gruvbox'
