syntax on
set encoding=utf-8

set nobackup
set nowritebackup
set noswapfile

set number
set relativenumber

set shiftwidth=4
set tabstop=4
set softtabstop=4

set expandtab
set smartindent
set breakindent
